Remove subscription
ros2/rclc pull request #106
Opened 2021-06-30 01:49 UTC by BrettRD

This allows subscriptions (and other callbacks) to be removed from the executor
It's been a while since I worked on this, I'll mark it as draft and re-base the commit

2021-06-30 11:07 UTC, BrettRD commented
This is ready for review

2021-07-02 14:01 UTC, JanStaschulat requested changes
Source code looks great to me. Some remarks: 
- By copying the values, the order of handels is preserved. That is good (because this defines the processing order of callbacks in the the spin methods). 
- You initialize the handle (which was copied to the n-1th element, good!
- test case, handle_list_size=1, remove one subscription
- memory of the handle is not freed because it is allocated elsewhere (in main), OK

Could you please add some more test cases for removing subscriptions:
- handle_list: [a,b,c], remove a
- handle_list: [a,b,c], remove b
- handle_list: [a,b,c], remove c

Could you add one test case each for 
- removing timer
- guard_condition
- service
- client

correct DCO errors as described in 'Details' https://github.com/ros2/rclc/pull/106/checks?check_run_id=2948178382

2021-07-02 14:31 UTC, JanStaschulat commented
I had to update the build jobs for foxy branch: 
- updated ci job (GPG incident) 
- removed Dashing from build jobs 
in this PR: https://github.com/ros2/rclc/pull/110

once merged into branch foxy, please pull and merge into your PRs.

2021-07-05 04:23 UTC, BrettRD commented
New tests: removal of handles at every meaningful position in the executor handle list and their effect on list order, API tests for every other handle type.

I jumped the gun on your CI fix and I'm getting a merge conflict doing a bulk-sign-off, so I'll wait for https://github.com/ros2/rclc/pull/110 to hit foxy before sorting that out.

2021-07-05 08:18 UTC, JanStaschulat requested changes

2021-07-05 08:18 UTC, JanStaschulat commented on rclc/test/rclc/test_executor.cpp
> +
```suggestion
  EXPECT_EQ(executor.handles[0].subscription, &this->sub1) <<
    "expect to find sub1 in first handle";
  EXPECT_EQ(executor.handles[1].subscription, &this->sub2) <<
    "expect to find sub2 in second handle";
```

2021-07-05 08:18 UTC, JanStaschulat commented on rclc/test/rclc/test_executor.cpp
> +
```suggestion
  EXPECT_EQ(executor.handles[0].subscription, &this->sub1) <<
    "expect to find sub1 in first handle";
  EXPECT_EQ(executor.handles[1].subscription, &this->sub3) <<
    "expect to find sub3 in second handle";
```

2021-07-05 08:18 UTC, JanStaschulat commented on rclc/test/rclc/test_executor.cpp
> +
```suggestion
  EXPECT_EQ(executor.handles[0].subscription, &this->sub3) <<
    "expect to find sub3 in first handle";
  EXPECT_EQ(executor.handles[1].subscription, &this->sub2) <<
    "expect to find sub2 in second handle";
```

2021-07-05 08:18 UTC, JanStaschulat commented on rclc/test/rclc/test_executor.cpp
> +
I added this test directly after the remove-operation folowing the principle: one method-call (here `rclc_executor_remove_subscription`) then test expected value with actual value. I saw, of course, that you test the same after adding the subscription again at the end.

2021-07-05 08:21 UTC, JanStaschulat commented
@BrettRD PR #110 is merged. You can ignore the failing buld job for Dashing, it is no longer relevant. Thanks for adding the test cases. Just added the test directly after the `remove`operation.

2021-07-05 11:27 UTC, BrettRD commented
@JanStaschulat Thanks for the suggestions!

I didn't expect such a mess after the recommended signoff procedure!
That rebase made the files-changed tab almost unreadable

2021-07-05 11:42 UTC, JanStaschulat commented
Hmm, something went wrong with updating DCO. Now it unfortunately contains many other files.

2021-07-05 13:47 UTC, BrettRD commented
> Could you do a rebase on current Foxy branch first?

That looks *much* better.

2021-07-05 14:12 UTC, JanStaschulat approved these changes

2021-07-05 14:13 UTC, merged

2021-07-08 13:46 UTC, JanStaschulat commented
@mergify backport galactic master

2021-07-17 07:18 UTC, JanStaschulat commented
solves https://github.com/ros2/rclc/issues/50

2022-05-25 17:21 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-humble-hawksbill-released/25729/14