Adds service callback with service context
ros2/rclc pull request #37
Opened 2021-01-22 14:52 UTC by norro

Adds an additional callback type and handling that allows passing
additional service context (void *) to a service callback.

https://github.com/ros2/rclc/issues/35

2021-01-25 09:41 UTC, norro commented
@JanStaschulat can you have a look at the failing tests, e.g., [in rolling](https://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/60/)?
1. I don't get the reason for the non-equalities, maybe you can give me a hint
1. I have different tests failing in my local rolling setup. This might indicate, that these tests are generally unstable?

2021-01-25 10:15 UTC, JanStaschulat commented
@norro Please create a pull request to micro-ros/rclc. The default configuration is ros2/rclc, therefore you always have to change the repository to which you want to create a pull request to. 

I looked briefly at the output errors. These are all from the th OSRF/OpenRobotics build farm and not the github action build job. I know that some test cases of the rclc executor fail sometimes due to timing issues at the OSRF build farm. I don't have a solution for that yet. Sometimes they get through sometimes not. 

For the Eloquent build job, there seems to be a problem with the docker container, as 'ament_cmake_ros' package is not found. We will remove Eloquent from our tests, as Eloquent will not be supported any more.

2021-01-25 10:20 UTC, JanStaschulat requested changes
Only minor improvements.

2021-01-25 10:20 UTC, JanStaschulat commented on rclc/src/rclc/executor.c
> +      RCL_SET_ERROR_MSG("Could not reset wait_set in rclc_executor_add_service function.");
```suggestion
      RCL_SET_ERROR_MSG("Could not reset wait_set in rclc_executor_add_service_with_context function.");
```

2021-01-25 10:20 UTC, JanStaschulat commented on rclc/src/rclc/executor.c
> +  RCUTILS_LOG_DEBUG_NAMED(ROS_PACKAGE_NAME, "Added a service.");
```suggestion
  RCUTILS_LOG_DEBUG_NAMED(ROS_PACKAGE_NAME, "Added a service_with_context.");
```

2021-01-25 10:43 UTC, JanStaschulat commented
> @JanStaschulat can you have a look at the failing tests, e.g., [in rolling](https://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/60/)?
> 
>     1. I don't get the reason for the non-equalities, maybe you can give me a hint
> 
>     2. I have different tests failing in my local rolling setup. This might indicate, that these tests are generally unstable?

I know that sporadically these units tests fail. This is a timing issue. For now, just ignore these error from trigger_one trigger_always trigger_once etc. In next sprint (February) I will try to re-write them. On my native Linux and at the CI github action on both micro-ros and ros2/rclc they always work. Only at the build farm of OSRF they fail. It is interesting that they also fail at your local machine. Could you please list the unit test, that fail?

2021-01-26 08:35 UTC, norro commented
Created a PR in micro-ros/rclc against micro-ros/rclc master: https://github.com/micro-ROS/rclc/pull/68

2021-01-26 08:35 UTC, closed without merging