depricate master branch
ros2/rclc pull request #376
Opened 2023-06-21 10:16 UTC by JanStaschulat

added notice statement in README.

2023-06-21 17:12 UTC, pablogs9 requested changes

2023-06-21 17:12 UTC, pablogs9 commented on README.md
> +The master branch is depricated. Following ROS 2 naming conventions, the rolling branch is now the active development branch.
```suggestion
The master branch is deprecated. Following ROS 2 naming conventions, the `rolling` branch is now the active development branch. 
```

2023-06-22 07:17 UTC, JanStaschulat commented on README.md
> +The master branch is deprecated. Following ROS 2 naming conventions, the `rolling` branch is now the active development branch.
```suggestion
The master branch is deprecated. Following [ROS 2 naming conventions](https://discourse.ros.org/t/change-default-branch-name-to-rolling-in-ros-2-core/26009), the `rolling` branch is now the active development branch. 
```

2023-06-23 13:12 UTC, pablogs9 approved these changes

2023-06-23 15:16 UTC, merged